services:
  monotes:
    container_name: monotes-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - monotes-data:/data
    restart: no
    healthcheck:
      test: ["CMD", "/app/curl", "-f", "http://0.0.0.0:8000/health"]
  
volumes:
  monotes-data:
    driver: local

networks:
  default:
    name: monotes-network
    external: false