services:
  monotes:
    container_name: monotes-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: never
    tty: true
    stdin_open: true
    networks:
      - default
    ports:
      - 7999:7999

networks:
  default:
    name: monotes-network
    external: false
